name: buildfork 
on: 
  push:
    branches:
      - main
jobs: 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://melted-chickens07.surge.sh
    steps:
      - name: Download the build artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: build
      - name: deploy to surge
        run: npx surge --project '.' --domain melted-chickens07.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4.2.2
      - name: Cache 
        uses: actions/cache@v4.2.3
        with: 
          path: ~/.npm 
          key: buildCache 
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: upload code coverage
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: codecoverage 
          path: coverage 
      - name: build 
        run: npm run build 
      - name: Upload build files 
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: build 
          path: build
